### ISSUE TITLE
Avalible for hire?

### ISSUE THREAD

**Issue by fresh83** [whaatt/Pyak#1]
If so email: Chuck@buhz.com

**Comment by whaatt** [comment]
Hi, thanks for contacting me! I'm curious what for, and whether this pertains at all to this repository.

**Comment by fresh83** [comment]
Yeah a bit …im the co-founder of www.buhz.com  - same type of content , same demo , just not anonymous and centered around helping students find their sense of belonging . We just raised our first round of funding and could use ur talents.

—
